### ISSUE TITLE
배포 자동화 및 배치 주체 변경

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/KOIN_BATCH#39]
## Description
KOIN_BATCH에도 배포 자동화 도입 및 배치 주체를 변경함.

참고: [기존 진행했던 문서](https://docs.google.com/document/d/1bJAz9iQpReMjVkK2cSnRxI3aA_hRNG2iylJvm1DmkV4/edit)

**as-is**
- 배포 방법: 로컬에서 코드 변경이후 Github에 Push한 후 서버 인스턴스에서 이를 다시 Pull 받아 활용하였음.
- 배치 스크립트 실행 방법: 서버 인스턴스의 crontab에서 실행
**to-be**
- 배포 방법: 젠킨스를 활용하여 배포를 자동화함.
- 배치 스크립트 실행 방법: 젠킨스 내부에서 배치를 처리함.
## Task List

- [x] 배포 자동화를 도입한다.
  - [x] (버스 시간표) 젠킨스에서 Go 파일 Build한 후 결과물만 서버에 넣어준다. (문서 댓글의 내용 참고)
  - [x] (크롤링) py 파일들의 변경내용을 서버에 반영한다.
- [x] 배치 스크립트
  - [x] 공지사항, 식단의 크롤링을 젠킨스의 배치 스크립트를 이용함.
    - 참고: [코인 cron](https://drive.google.com/drive/folders/1r95PE3DI8F0Mj_7KZsX19IGGPpglnGap)

## Remark

- 스테이지의 파일이 올라가는 것 까지는 진행되었음. (배포 자동화까지) [프로덕션은 X]
- 기존 배치파일을 실행하던 사용자가 아닌 새로운 사용자가 배치 파일들을 실행하기에 mysql 등의 라이브러리가 있어야 함. (배치 파일들 실행 안됨)
